site_name: teste mkdocs
site_description: teste do mkdocs
site_author: a3data
copyright: a3data

nav:
    - Home: index.md

theme:
    name: material

    language: pt
    favicon: 
    logo:
    features: 
      - search.suggest
      - search.highlight
    palette:
      - scheme: default
        primary: blue
        accent: yellow
        toggle:
            icon: material/toggle-switch-off-outline
            name: Modo Escuro
      - scheme: slate
        primary: white
        toggle:
            icon: material/toggle-switch
            name: Modo Claro
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 1 # Nível básico dos cabeçalhos
        separator: "_"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys